model:
  name: feedforward
  input_size: 784
  hidden_size: 500
  num_classes: 10
  onnx_parameters:
    export_to_onnx: True
    onnx_path: ./models/best_model.onnx
    mlflow_onnx_export_path: ./models/onnx_model
    input_shape: [1, 784]

data:
  model_path: ./models/model.pth
  preds_path: ./predictions/answers.csv
  train_data_file: ./data/MNIST/raw/train-images-idx3-ubyte
  train_labels_file: ./data/MNIST/raw/train-labels-idx1-ubyte
  test_data_file: ./data/MNIST/raw/t10k-images-idx3-ubyte
  test_labels_file: ./data/MNIST/raw/t10k-labels-idx1-ubyte

train:
  num_epochs: 2
  batch_size: 128
  learning_rate: 0.001
  seed: 123

infer:
  batch_size: 128
  inference_port: 8891
  inference_addr: http://127.0.0.1:8891

loggers:
  mlflow:
    experiment_name: exp_1
    tracking_uri: http://localhost:8890
